import{a as b,S as L,i as M}from"./assets/vendor-b0d10f48.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const v="44841461-2c7fd944dee0b14672f32444a";async function u({q:e="",page:n=1,per_page:a=15}={}){return(await b.get("https://pixabay.com/api/",{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:a}})).data}function p(e){return e.map(({largeImageURL:a,webformatURL:l,tags:t,views:o,downloads:c,likes:g,comments:y})=>`<li class="gallery-item">
    <a  class="gallery-link" href=${a}><img src="${l}" alt="${t}" title="${t}" width="360" height="200"></a>
    <div>
      <ul class="description-list">
        <li><p class="description-element">Like<br><span>${g}</span></p></li>
        <li><p class="description-element">Views<br><span>${o}</span></p></li>
        <li><p class="description-element">Comments<br><span>${y}</span></p></li>
        <li><p class="description-element">Downloads<br><span>${c}</span></p></li>
      </ul>
      </img>
  </li>
  </div>`).join(" ")}const m="is-hidden";function S(e){e.classList.add(m)}function B(e){e.classList.remove(m)}function $(e){e.disabled=!0}function q(e){e.disabled=!1}const s={hide:S,show:B,disabled:$,enable:q},r={gallery:document.querySelector(".gallery"),form:document.querySelector(".js-form"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".js-load-more"),spinner:document.querySelector(".loader")},w="Sorry, please enter text",x="Sorry, there are not no images matching your search query",f="Oops",i={q:"",page:1,per_page:15,maxPage:0};s.hide(r.loadMoreBtn);r.form.addEventListener("submit",E);r.loadMoreBtn.addEventListener("click",h);const P=new L(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"});function E(e){if(e.preventDefault(),r.gallery.innerHTML="",i.page=1,i.q=e.currentTarget.children.query.value,!i.q.trim().length)return d("Warning",w);r.loader.classList.remove("visually-hidden"),u(i).then(({total:n,totalHits:a,hits:l})=>{i.maxPage=Math.ceil(a/i.per_page),r.gallery.insertAdjacentHTML("beforeend",p(l)),P.refresh(),s.show(r.loadMoreBtn),s.disabled(r.loadMoreBtn),l.length>0&&l.length*i.page!==a?s.enable(r.loadMoreBtn):(d("Warning",x),s.hide(r.loadMoreBtn))}).catch(n=>d("Error",f,n)).finally(()=>{r.loader.classList.add("visually-hidden"),r.form.reset()})}function h(){i.page+=1;const e=r.loadMoreBtn.nextElementSibling;e.classList.remove("visually-hidden"),u(i).then(({hits:n})=>{r.gallery.insertAdjacentHTML("beforeend",p(n)),O()}).catch(n=>d("Error",f,n)).finally(()=>{s.enable(r.loadMoreBtn),e.classList.add("visually-hidden"),i.page===i.maxPage&&(s.hide(r.loadMoreBtn),r.loadMoreBtn.removeAttribute("click",h),d("Error","We're sorry, but you've reached the end of search results."))})}function d(e,n,a=null){return M.warning({title:`${e}`,message:a?`${n} ${a} `:`${n}`})}function O(){const e=r.gallery.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
