import{a as S,S as w,i as $}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function n(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function s(r){if(r.ep)return;r.ep=!0;const i=n(r);fetch(r.href,i)}})();const q="44841461-2c7fd944dee0b14672f32444a";async function m({q:e="",page:t=1,per_page:n=15}={}){return(await S.get("https://pixabay.com/api/",{params:{key:q,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}function f(e){return e.map(({largeImageURL:n,webformatURL:s,tags:r,views:i,downloads:d,likes:L,comments:v})=>`<li class="gallery-item">
    <a  class="gallery-link" href=${n}><img src="${s}" alt="${r}" title="${r}" width="360" height="200"></a>
    <div>
      <ul class="description-list">
        <li><p class="description-element">Like<br><span>${L}</span></p></li>
        <li><p class="description-element">Views<br><span>${i}</span></p></li>
        <li><p class="description-element">Comments<br><span>${v}</span></p></li>
        <li><p class="description-element">Downloads<br><span>${d}</span></p></li>
      </ul>
      </img>
  </li>
  </div>`).join(" ")}const h="is-hidden";function E(e){e.classList.add(h)}function M(e){e.classList.remove(h)}function P(e){e.disabled=!0}function x(e){e.disabled=!1}const l={hide:E,show:M,disabled:P,enable:x},O={gallery:document.querySelector(".gallery"),form:document.querySelector(".js-form"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".js-load-more"),spinner:document.querySelector(".loader")},A="Sorry, please enter text",C="Sorry, there are not no images matching your search query",g="Oops",{gallery:c,form:y,loader:p,loadMoreBtn:a}=O,o={q:"",page:1,per_page:15,maxPage:0};l.hide(a);y.addEventListener("submit",k);c.addEventListener("click",j);function j(e){e.preventDefault(),e.target.nodeName==="IMG"&&new w(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"})}function k(e){if(e.preventDefault(),c.innerHTML="",o.page=1,o.q=e.currentTarget.children.query.value,!o.q.trim().length)return u("Warning",A);p.classList.remove("visually-hidden"),m(o).then(({total:t,totalHits:n,hits:s})=>{o.maxPage=Math.ceil(n/o.per_page),c.insertAdjacentHTML("beforeend",f(s)),l.show(a),l.disabled(a),s.length>0&&s.length*o.page!==n?(l.enable(a),a.addEventListener("click",b)):(u("Warning",C),l.hide(a))}).catch(t=>u("Error",g,t)).finally(()=>{p.classList.add("visually-hidden"),y.reset()})}function b(){o.page+=1,B();const e=a.nextElementSibling;e.classList.remove("visually-hidden"),m(o).then(({hits:t})=>{c.insertAdjacentHTML("beforeend",f(t))}).catch(t=>u("Error",g,t)).finally(()=>{l.enable(a),e.classList.add("visually-hidden"),o.page===o.maxPage&&(l.hide(a),a.removeAttribute("click",b),u("Error","We're sorry, but you've reached the end of search results."))})}function u(e,t,n=null){return $.warning({title:`${e}`,message:n?`${t} ${n} `:`${t}`})}function B(){const t=c.lastElementChild.getBoundingClientRect(),n=c.getBoundingClientRect();window.scrollBy({top:t.top-n.top+window.scrollY,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
