import{a as L,S as M,i as v}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))d(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const S="44841461-2c7fd944dee0b14672f32444a";async function u({q:e="",page:t=1,per_page:s=15}={}){return(await L.get("https://pixabay.com/api/",{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}})).data}function p(e){return e.map(({largeImageURL:s,webformatURL:d,tags:r,views:n,downloads:l,likes:g,comments:b})=>`<li class="gallery-item">
    <a  class="gallery-link" href=${s}><img src="${d}" alt="${r}" title="${r}" width="360" height="200"></a>
    <div>
      <ul class="description-list">
        <li><p class="description-element">Like<br><span>${g}</span></p></li>
        <li><p class="description-element">Views<br><span>${n}</span></p></li>
        <li><p class="description-element">Comments<br><span>${b}</span></p></li>
        <li><p class="description-element">Downloads<br><span>${l}</span></p></li>
      </ul>
      </img>
  </li>
  </div>`).join(" ")}const m="is-hidden";function w(e){e.classList.add(m)}function B(e){e.classList.remove(m)}function $(e){e.disabled=!0}function q(e){e.disabled=!1}const i={hide:w,show:B,disabled:$,enable:q},o={gallery:document.querySelector(".gallery"),form:document.querySelector(".js-form"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".js-load-more"),spinner:document.querySelector(".loader")},x="Sorry, please enter text",P="Sorry, there are not no images matching your search query",h="Oops",a={q:"",page:1,per_page:15,maxPage:0};i.hide(o.loadMoreBtn);o.form.addEventListener("submit",E);o.loadMoreBtn.addEventListener("click",y);const f=new M(".gallery a",{captionDelay:250,captionPosition:"bottom",captionsData:"alt"});async function E(e){if(e.preventDefault(),o.gallery.innerHTML="",a.page=1,a.q=e.currentTarget.children.query.value,!a.q.trim().length)return c("Warning",x);o.loader.classList.remove("visually-hidden");try{const t=await u(a);a.maxPage=Math.ceil(t.totalHits/a.per_page),o.gallery.insertAdjacentHTML("beforeend",p(t.hits)),f.refresh(),i.show(o.loadMoreBtn),i.disabled(o.loadMoreBtn),t.hits.length>0&&t.hits.length*a.page!==t.totalHits?i.enable(o.loadMoreBtn):(c("Warning",P),i.hide(o.loadMoreBtn))}catch(t){c("Error",h,t),console.log(t)}finally{o.loader.classList.add("visually-hidden"),o.form.reset()}}async function y(){a.page+=1;const e=o.loadMoreBtn.nextElementSibling;e.classList.remove("visually-hidden");try{const t=await u(a);o.gallery.insertAdjacentHTML("beforeend",p(t.hits)),f.refresh(),O()}catch(t){c("Error",h,t)}finally{i.enable(o.loadMoreBtn),e.classList.add("visually-hidden"),a.page===a.maxPage&&(i.hide(o.loadMoreBtn),o.loadMoreBtn.removeAttribute("click",y),c("Error","We're sorry, but you've reached the end of search results."))}}function c(e,t,s=null){return v.warning({title:`${e}`,message:s?`${t} ${s} `:`${t}`})}function O(){const e=o.gallery.lastElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
